### ISSUE TITLE
Spacing above h2/other headings

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#109]
Relevant to w3c/wai-intro-accessibility#5

@@link to wiki page@@

**Comment by shawna-slh** [comment]
[ link to wiki page: https://www.w3.org/WAI/EO/wiki/Redesign_-_October_Revisions#Visual_design ]

Spacing above h2s looks good now. Seems too much above h3s. e.g., see: https://w3c.github.io/wai-older-users/older-users/literature/#summary-of-impact-and-prevalence

**Comment by yatil** [comment]
@slhenry How much spacing would you like to have above 

* [ ] h3
* [ ] h4
* [ ] h5
* [ ] h6

? 

Currently we have [these margins (click the assets tab on the bottom)](https://w3c.github.io/wai-website-components/components/detail/headings.html): 

```css
h1, h2, h3 {
  padding: 0;
  margin: 60px 0 20px;
}

h4, h5, h6 {
  padding: 0;
  margin: 20px 0 10px;
}
```

**Comment by yatil** [comment]
Changed to

```css
h1, h2     { margin: 60px 0 20px; }
h3         { margin: 40px 0 20px; }
h4, h5, h6 { margin: 20px 0 10px; }
```
